### ISSUE TITLE
Can't read HDR file

### ISSUE THREAD

**Issue by abbaswasim** [xiaozhuai/imageinfo#3]
IIUC it should be able to identify and read HDR files but running `imageinfo` https://github.com/KhronosGroup/glTF-Sample-Environments/blob/b710a9fe6bcdfb8965530ede36e8279c298261de/footprint_court.hdr gives error 

```
  - Error    : Unrecognized image format
```

**Comment by xiaozhuai** [comment]
Thanks for report this bug, it was fixed by https://github.com/xiaozhuai/imageinfo/commit/4fe7ec088785091ac2cf5f72b72ccdc7b7ba1fa5
